linux server https://ubuntu.com/download/server (new verison recommendation 22.04.x TLS)
vm ware workstation or virtualbox link below
vm ware https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html (need need)  https://gist.github.com/PurpleVibe32/30a802c3c8ec902e1487024cdea26251
virtualbox https://www.virtualbox.org/ (no need keygen)
browser chrome, firefox, edge ,and another
internet connection
SSH include in linux ubuntu server (openSSH)
PHP
mysql
PC or Laptop medium spec
